//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.UnitTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Test_Code_FirstEntities : DbContext
    {
        public Test_Code_FirstEntities()
            : base("name=Test_Code_FirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<WebConfirmRecords> WebConfirmRecords { get; set; }
        public DbSet<WebDataCtrls> WebDataCtrls { get; set; }
        public DbSet<WebDataSettings> WebDataSettings { get; set; }
        public DbSet<WebDepartments> WebDepartments { get; set; }
        public DbSet<WebLoggers> WebLoggers { get; set; }
        public DbSet<WebManageMenus> WebManageMenus { get; set; }
        public DbSet<WebManageRoles> WebManageRoles { get; set; }
        public DbSet<WebManageRoles_WebManageMenus_Authority_R> WebManageRoles_WebManageMenus_Authority_R { get; set; }
        public DbSet<WebManageUsers> WebManageUsers { get; set; }
    }
}
