//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebDepartments :Lind.DDD.Domain.IEntity
    {
        public WebDepartments()
        {
            this.WebDataSettings = new HashSet<WebDataSettings>();
            this.WebDepartments1 = new HashSet<WebDepartments>();
            this.WebManageRoles = new HashSet<WebManageRoles>();
            this.WebManageUsers = new HashSet<WebManageUsers>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string About { get; set; }
        public int SortNumber { get; set; }
        public string Operator { get; set; }
        public int Level { get; set; }
        public Nullable<int> ParentID { get; set; }
        public System.DateTime DataCreateDateTime { get; set; }
        public System.DateTime DataUpdateDateTime { get; set; }
        public int DataStatus { get; set; }
    
        public virtual ICollection<WebDataSettings> WebDataSettings { get; set; }
        public virtual ICollection<WebDepartments> WebDepartments1 { get; set; }
        public virtual WebDepartments WebDepartments2 { get; set; }
        public virtual ICollection<WebManageRoles> WebManageRoles { get; set; }
        public virtual ICollection<WebManageUsers> WebManageUsers { get; set; }
    }
}
