//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebDataSettings :Lind.DDD.Domain.IEntity
    {
        public int ID { get; set; }
        public int WebDataCtrlId { get; set; }
        public int WebManageRolesId { get; set; }
        public string ObjectIdArr { get; set; }
        public System.DateTime DataCreateDateTime { get; set; }
        public System.DateTime DataUpdateDateTime { get; set; }
        public int DataStatus { get; set; }
        public Nullable<int> WebDepartments_Id { get; set; }
    
        public virtual WebDataCtrls WebDataCtrls { get; set; }
        public virtual WebDepartments WebDepartments { get; set; }
        public virtual WebManageRoles WebManageRoles { get; set; }
    }
}
