//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebManageMenus :Lind.DDD.Domain.IEntity
    {
        public WebManageMenus()
        {
            this.WebManageMenus1 = new HashSet<WebManageMenus>();
            this.WebManageRoles_WebManageMenus_Authority_R = new HashSet<WebManageRoles_WebManageMenus_Authority_R>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Level { get; set; }
        public string LinkUrl { get; set; }
        public string About { get; set; }
        public int SortNumber { get; set; }
        public string Operator { get; set; }
        public bool IsDisplayMenuTree { get; set; }
        public Nullable<int> ParentID { get; set; }
        public System.DateTime DataCreateDateTime { get; set; }
        public System.DateTime DataUpdateDateTime { get; set; }
        public int DataStatus { get; set; }
    
        public virtual ICollection<WebManageMenus> WebManageMenus1 { get; set; }
        public virtual WebManageMenus WebManageMenus2 { get; set; }
        public virtual ICollection<WebManageRoles_WebManageMenus_Authority_R> WebManageRoles_WebManageMenus_Authority_R { get; set; }
    }
}
