//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebManageRoles :Lind.DDD.Domain.IEntity
    {
        public WebManageRoles()
        {
            this.WebDataSettings = new HashSet<WebDataSettings>();
            this.WebManageRoles_WebManageMenus_Authority_R = new HashSet<WebManageRoles_WebManageMenus_Authority_R>();
            this.WebManageUsers = new HashSet<WebManageUsers>();
        }
    
        public int ID { get; set; }
        public string RoleName { get; set; }
        public string About { get; set; }
        public int SortNumber { get; set; }
        public string Operator { get; set; }
        public int DepartmentID { get; set; }
        public System.DateTime DataCreateDateTime { get; set; }
        public System.DateTime DataUpdateDateTime { get; set; }
        public int DataStatus { get; set; }
    
        public virtual ICollection<WebDataSettings> WebDataSettings { get; set; }
        public virtual WebDepartments WebDepartments { get; set; }
        public virtual ICollection<WebManageRoles_WebManageMenus_Authority_R> WebManageRoles_WebManageMenus_Authority_R { get; set; }
        public virtual ICollection<WebManageUsers> WebManageUsers { get; set; }
    }
}
