//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebManageUsers :Lind.DDD.Domain.IEntity
    {
        public WebManageUsers()
        {
            this.WebDepartments = new HashSet<WebDepartments>();
            this.WebManageRoles = new HashSet<WebManageRoles>();
        }
    
        public int ID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string RealName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string Operator { get; set; }
        public Nullable<int> WebSystemID { get; set; }
        public string ThridUserId { get; set; }
        public System.DateTime DataCreateDateTime { get; set; }
        public System.DateTime DataUpdateDateTime { get; set; }
        public int DataStatus { get; set; }
    
        public virtual ICollection<WebDepartments> WebDepartments { get; set; }
        public virtual ICollection<WebManageRoles> WebManageRoles { get; set; }
    }
}
