//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.Manager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class WebDepartments : Lind.DDD.Domain.Entity, Lind.DDD.TreeHelper.ITree<WebDepartments>
    {
        public WebDepartments()
        {
            this.WebManageRoles = new List<WebManageRoles>();
            this.WebManageUsers = new List<WebManageUsers>();
            this.Sons = new List<WebDepartments>();
            this.LinkUrl = string.Empty;
        }
        [DisplayName("部门名称"), Required]
        public string Name { get; set; }
        [DisplayName("描述")]
        public string About { get; set; }
        [DisplayName("排序"), Required]
        public int SortNumber { get; set; }
        [DisplayName("操作者")]
        public string Operator { get; set; }
        [DisplayName("級別"), Required]
        public int Level { get; set; }
        [DisplayName("父ID")]
        public Nullable<int> ParentID { get; set; }

        public virtual IList<WebDepartments> Sons { get; set; }
        public virtual WebDepartments Father { get; set; }
        public virtual IList<WebManageRoles> WebManageRoles { get; set; }
        public virtual IList<WebManageUsers> WebManageUsers { get; set; }

        #region ITree 成员


        public bool IsLeaf
        {
            get { return this.Sons == null || this.Sons.Count == 0; }
        }
        /// <summary>
        /// 不序列化到数据库
        /// </summary>
        [NotMapped]
        public string LinkUrl
        {
            get;
            set;
        }

        /// <summary>
        /// 不序列化到数据库
        /// </summary>
        [NotMapped]
        public long Authority
        {
            get;
            set;
        }

        #endregion
    }
}
