//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.Manager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class WebManageUsers : Lind.DDD.Domain.Entity
    {
        public WebManageUsers()
        {
            this.WebManageRoles = new HashSet<WebManageRoles>();
            this.WebDepartments = new HashSet<WebDepartments>();
        }
        [DisplayName("登陆名"), Required]
        public string LoginName { get; set; }
        [DisplayName("密码"), Required]
        public string Password { get; set; }
        [DisplayName("真实姓名"), Required]
        public string RealName { get; set; }
        [DisplayName("手机"), Required]
        public string Mobile { get; set; }
        [DisplayName("电子邮件"), Required]
        public string Email { get; set; }
        [DisplayName("描述")]
        public string Description { get; set; }
        [DisplayName("操作者")]
        public string Operator { get; set; }
        [DisplayName("所属项目")]
        public Nullable<int> WebSystemID { get; set; }
        /// <summary>
        /// 第三方相关编号
        /// </summary>
        [DisplayName("员工工号")]
        public string ThridUserId { get; set; }

        public virtual ICollection<WebManageRoles> WebManageRoles { get; set; }
        public virtual ICollection<WebDepartments> WebDepartments { get; set; }
    }
}
