//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.Manager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class WebManageMenus : Lind.DDD.Domain.Entity, Lind.DDD.TreeHelper.ITree<WebManageMenus>
    {
        public WebManageMenus()
        {
            this.Sons = new List<WebManageMenus>();
            this.WebManageRoles_WebManageMenus_Authority_R = new List<WebManageRoles_WebManageMenus_Authority_R>();
            this.IsDisplayMenuTree = true;
        }

        [DisplayName("菜单名称"), Required]
        public string Name { get; set; }
        [DisplayName("级别"), Required]
        public int Level { get; set; }
        [DisplayName("链接地址")]
        public string LinkUrl { get; set; }
        [DisplayName("描述")]
        public string About { get; set; }
        [DisplayName("排序"), Required]
        public int SortNumber { get; set; }
        [DisplayName("操作者")]
        public string Operator { get; set; }
        [DisplayName("是否显示在菜单树上"), Required]
        public bool IsDisplayMenuTree { get; set; }
        [DisplayName("父ID")]
        public Nullable<int> ParentID { get; set; }
        /// <summary>
        /// 在菜单对应的页面上显示的命令按钮列表，64位无符号，操作删除，这个位将被回收
        /// </summary>
        [DisplayName("命令按钮")]
        public long Authority { get; set; }
        public virtual IList<WebManageMenus> Sons { get; set; }
        public virtual WebManageMenus Father { get; set; }
        public virtual ICollection<WebManageRoles_WebManageMenus_Authority_R> WebManageRoles_WebManageMenus_Authority_R { get; set; }

        #region ITree 成员


        public bool IsLeaf
        {
            get { return this.Sons == null || this.Sons.Count == 0; }
        }

        #endregion
    }
}
