//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.Manager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class WebManageRoles : Lind.DDD.Domain.Entity
    {
        public WebManageRoles()
        {
            this.WebManageUsers = new List<WebManageUsers>();
            this.WebManageRoles_WebManageMenus_Authority_R = new List<WebManageRoles_WebManageMenus_Authority_R>();
            this.WebDataSetting = new List<WebDataSetting>();
        }
        [DisplayName("角色名称"), Required]
        public string RoleName { get; set; }
        [DisplayName("关于")]
        public string About { get; set; }
        [DisplayName("排序"), Required]
        public int SortNumber { get; set; }
        [DisplayName("最后操作人")]
        public string Operator { get; set; }
        [DisplayName("部门"), Required]
        public int DepartmentID { get; set; }

        public virtual WebDepartments WebDepartments { get; set; }
        public virtual ICollection<WebManageRoles_WebManageMenus_Authority_R> WebManageRoles_WebManageMenus_Authority_R { get; set; }
        public virtual ICollection<WebDataSetting> WebDataSetting { get; set; }
        public virtual ICollection<WebManageUsers> WebManageUsers { get; set; }
    }
}
