//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artists
    {
        public Artists()
        {
            this.Audio = new HashSet<Audio>();
        }
    
        public System.Guid Id { get; set; }
        public int Age { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Audio> Audio { get; set; }
    }
}
