//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audio
    {
        public System.Guid Id { get; set; }
        public System.Guid ArtistId { get; set; }
        public string Name { get; set; }
        public string Src { get; set; }
        public int Type { get; set; }
    
        public virtual Artists Artists { get; set; }
    }
}
