//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.DDD.Test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EF7_testEntities : DbContext
    {
        public EF7_testEntities()
            : base("name=EF7_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public DbSet<Artists> Artists { get; set; }
        public DbSet<Audio> Audio { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<tbl_MBS_Marks> tbl_MBS_Marks { get; set; }
        public DbSet<tbl_MBS_ObjectMarks> tbl_MBS_ObjectMarks { get; set; }
        public DbSet<tbl_MBS_Parallel_Execution_Log> tbl_MBS_Parallel_Execution_Log { get; set; }
        public DbSet<tbl_MBS_Profile> tbl_MBS_Profile { get; set; }
        public DbSet<tbl_MBS_SelectIntoTables> tbl_MBS_SelectIntoTables { get; set; }
        public DbSet<tbl_MBS_SpecialObjects> tbl_MBS_SpecialObjects { get; set; }
        public DbSet<tbl_MBS_SystemObject> tbl_MBS_SystemObject { get; set; }
        public DbSet<User> User { get; set; }
    }
}
