#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Lind.DDD.Android.Resource", IsApplication=true)]

namespace Lind.DDD.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int anliyu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int chu = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int da = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int li = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ling = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int miao = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ming = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ning = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int song = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int zang = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int zhu = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int zou = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int MyButton = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int imgUser = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int listViewMain = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int textView1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textView2 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int textView3 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int textView4 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int textView5 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int textView6 = 2131034127;
			
			// aapt resource value: 0x7f050000
			public const int tlNames = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int tvAssistsCount = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int tvDesc = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int tvFails = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int tvLevel = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int tvName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int tvScore = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int userInfoViewMain = 2131034128;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChooseUserLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int UserInfoDetailLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int UserInfoLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int UserListItemLayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int AlipayNotify = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int Partner = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int Rsa_private = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int Seller = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int apiHost = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
